export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const SET_LOADING = 'SET_LOADING'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SET_THEME = 'SET_THEME'
